import React,{useMemo,useState} from 'react';
import {ArrowRight,CalendarDays,Check,ChevronDown,Clock3,Filter,Leaf,ShieldCheck,Ship,Star,Users,Wifi,Coffee,Wind} from 'lucide-react';
import {useLocation,useNavigate} from 'react-router-dom';
import {findRoute,getFerriesForRoute} from '../data/siteData';
import {Layout} from '../components/Layout';

const formatDate=date=>date?new Date(`${date}T00:00:00`).toLocaleDateString('en-IN',{day:'numeric',month:'long'}):'12 September';

function FerryResult({ferry,route}){
  const nav=useNavigate();
  const amenities=ferry.amenities;
  return <article className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm transition hover:-translate-y-0.5 hover:shadow-md sm:p-5">
    <div className="grid gap-4 lg:grid-cols-[1.1fr_1.05fr_.9fr_auto] lg:items-center">
      <div><span className="inline-flex rounded-full bg-[#d9f6ee] px-3 py-1 text-xs font-bold text-teal">{ferry.name==='SeaLink Express'?'Popular':ferry.name==='Island Queen'?'Comfort Ride':'Best for Views'}</span><h2 className="mt-2 text-lg font-black text-ocean">{ferry.name}</h2><div className="mt-2 flex flex-wrap gap-2">{amenities.map(amenity=><span className="inline-flex items-center gap-1.5 rounded-lg bg-[#edf8fa] px-2.5 py-1 text-xs font-semibold text-ocean" key={amenity}>{amenity==='Wi-Fi'?<Wifi size={13}/>:amenity==='Cafe'?<Coffee size={13}/>:<Wind size={13}/>} {amenity}</span>)}</div></div>
      <div className="flex items-center justify-between gap-3 border-y border-slate-100 py-3 sm:justify-start sm:gap-7 lg:border-y-0 lg:border-l lg:py-0 lg:pl-6"><div><b className="text-lg text-ocean">{ferry.depart}</b><p className="text-xs text-slate-500">{ferry.from}</p></div><Ship size={20} className="text-teal"/><div><b className="text-lg text-ocean">{ferry.arrive}</b><p className="text-xs text-slate-500">{ferry.to}</p></div></div>
      <div className="flex items-center gap-5 text-sm text-slate-500 lg:border-l lg:pl-6"><span><Clock3 size={16} className="mb-1 text-teal"/>{ferry.duration}</span><span className="font-bold text-ocean"><Star size={16} fill="currentColor" className="mb-1 text-amber-500"/>{ferry.rating} <small className="font-normal text-slate-400">(320 reviews)</small></span></div>
      <div className="flex items-center justify-between gap-4 lg:block lg:border-l lg:pl-6 lg:text-right"><span><b className="text-xl text-ocean">₹{ferry.price}</b><small className="block text-xs text-slate-400">per passenger</small></span><button type="button" onClick={()=>nav(`/ferry/${ferry.name.toLowerCase().replaceAll(' ','-')}?routeId=${encodeURIComponent(ferry.routeId)}&ferryName=${encodeURIComponent(ferry.name)}&people=${encodeURIComponent('2 Adults, 0 Children')}`)} className="btn-primary px-5 py-2.5">Select <ArrowRight size={15}/></button></div>
    </div>
  </article>;
}

export default function SearchPage(){
  const nav=useNavigate();
  const params=new URLSearchParams(useLocation().search);
  const route=findRoute({state:params.get('state')||'Maharashtra',from:params.get('from')||'Mumbai',to:params.get('to')||'Mandwa'});
  const [departure,setDeparture]=useState([]);
  const [amenities,setAmenities]=useState([]);
  const [sort,setSort]=useState('Departure time');
  const allFerries=route?getFerriesForRoute(route.id):[];
  const toggle=(value,setter,current)=>setter(current.includes(value)?current.filter(item=>item!==value):[...current,value]);
  const ferries=useMemo(()=>{let result=allFerries.filter(ferry=>(!departure.length||departure.some(period=>period==='Morning'&&ferry.depart.includes('AM')&&parseInt(ferry.depart)<12)||departure.some(period=>period==='Afternoon'&&ferry.depart.includes('PM')&&parseInt(ferry.depart)<5)||departure.some(period=>period==='Evening'&&ferry.depart.includes('PM')&&parseInt(ferry.depart)>=5))&&(!amenities.length||amenities.every(item=>ferry.amenities.includes(item))));return sort==='Price'?result.sort((a,b)=>a.price-b.price):result},[allFerries,departure,amenities,sort]);
  return <Layout><main className="bg-[#f4fafb]">
    <section className="relative min-h-[245px] overflow-hidden"><img src="/assets/images/search.png" alt="Ferry search results" className="absolute inset-0 h-full w-full object-cover"/><div className="absolute inset-0 bg-gradient-to-r from-[#063b4c]/90 via-[#063b4c]/45 to-transparent"/><div className="container-page relative z-10 flex min-h-[245px] items-center text-white"><div><p className="text-sm font-bold uppercase tracking-[0.25em] text-teal-100">Search results</p><h1 className="mt-3 text-4xl font-black sm:text-5xl">{route?`${route.from} → ${route.to}`:'Route unavailable'}</h1><div className="mt-4 flex flex-wrap gap-5 text-sm text-white/85"><span className="flex items-center gap-2"><CalendarDays size={17}/>{formatDate(params.get('date'))}</span><span className="flex items-center gap-2"><Users size={17}/>{params.get('people')||'2 Adults, 0 Children'}</span><button type="button" onClick={()=>nav('/#booking-search')} className="rounded-lg bg-white px-4 py-2 font-bold text-ocean">Edit search</button></div></div></div></section>
    <section className="container-page py-7"><div className="grid gap-6 lg:grid-cols-[245px_1fr]"><aside className="h-fit rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><h2 className="flex items-center gap-2 text-lg font-black text-ocean"><Filter size={18}/>Filters</h2><button type="button" onClick={()=>{setDeparture([]);setAmenities([])}} className="text-sm font-bold text-teal">Reset</button></div><div className="mt-5 border-t pt-5"><p className="flex items-center justify-between font-bold text-ocean">Departure time <ChevronDown size={16}/></p>{['Morning','Afternoon','Evening'].map(item=><label className="mt-3 flex gap-2 text-sm text-slate-600" key={item}><input type="checkbox" checked={departure.includes(item)} onChange={()=>toggle(item,setDeparture,departure)}/>{item}</label>)}</div><div className="mt-6 border-t pt-5"><p className="font-bold text-ocean">Amenities</p>{['AC','Wi-Fi','Cafe','Washroom'].map(item=><label className="mt-3 flex gap-2 text-sm text-slate-600" key={item}><input type="checkbox" checked={amenities.includes(item)} onChange={()=>toggle(item,setAmenities,amenities)}/>{item}</label>)}</div></aside><div><div className="mb-4 flex items-center justify-between gap-4"><p className="font-bold text-ocean">{ferries.length} ferries found</p><label className="flex items-center gap-2 text-sm text-slate-500">Sort by<select value={sort} onChange={event=>setSort(event.target.value)} className="rounded-lg border border-slate-200 bg-white px-3 py-2 font-semibold text-ocean"><option>Departure time</option><option>Price</option></select></label></div><div className="space-y-3">{ferries.map(ferry=><FerryResult ferry={ferry} route={route} key={`${ferry.routeId}-${ferry.name}`}/>)}</div>{!ferries.length&&<div className="rounded-2xl border border-dashed bg-white p-10 text-center text-slate-500">No ferries match these filters.</div>}<div className="mt-6 flex flex-col items-start justify-between gap-4 rounded-2xl bg-[#e8f8f7] p-6 sm:flex-row sm:items-center"><div className="flex items-center gap-4"><Leaf className="text-teal" size={36}/><div><h2 className="font-black text-ocean">Travel Better</h2><p className="text-sm text-slate-500">Safe, comfortable and scenic ferry journeys across India.</p></div></div><div className="flex gap-4 text-xs font-semibold text-teal"><span><ShieldCheck size={17}/></span><span><Leaf size={17}/></span></div></div></div></div></section>
  </main></Layout>;
}
