import React from 'react';
import {useNavigate} from 'react-router-dom';
import {ArrowRight,Clock3,Ship,Users} from 'lucide-react';
const popular=[
  {from:'Mumbai',to:'Mandwa',time:'1 hr',description:'A quick escape to serenity',feature:'Regular Ferries',detail:'Every 30 mins',second:'Scenic Journey',secondDetail:'Across the bay',img:'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=1000&q=85'},
  {from:'Mumbai',to:'Alibaug',time:'1.5 hrs',description:'Beaches, history and more',feature:'Comfortable Ride',detail:'AC & non-AC ferries',second:'Family Friendly',secondDetail:'Perfect getaway',img:'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1000&q=85'},
  {from:'Mumbai',to:'Elephanta',time:'1 hr',description:'Explore heritage by the sea',feature:'Frequent Ferries',detail:'Multiple slots',second:'Historic Caves',secondDetail:'UNESCO site',img:'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&w=1000&q=85'},
  {from:'Gateway',to:'Devgad',time:'6 hrs',description:'Two shores, one great journey',feature:'Overnight Ferries',detail:'Comfortable travel',second:'Scenic Coastline',secondDetail:'Beautiful views',img:'https://images.unsplash.com/photo-1500375592092-40eb2168fd21?auto=format&fit=crop&w=1000&q=85'},
];
export default function PopularRoutes(){const nav=useNavigate();return <section className="container-page bg-[#f4fbfc] py-12 sm:py-16"><div className="flex items-end justify-between gap-5"><div><p className="mb-1 text-sm font-black uppercase tracking-[0.18em] text-teal">Popular routes</p><h2 className="section-title text-[#0a3150]">Go farther by water</h2><p className="mt-2 text-sm text-slate-500">Discover scenic routes, charming coastal towns and unforgettable journeys.</p></div><button onClick={()=>nav('/routes')} className="hidden text-sm font-bold text-teal sm:block">View all routes →</button></div><div className="mt-7 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{popular.map(r=><button key={r.to} onClick={()=>nav('/search')} className="group overflow-hidden rounded-2xl border border-slate-200 bg-white text-left shadow-sm transition hover:-translate-y-1 hover:shadow-xl"><div className="relative h-64 overflow-hidden"><img src={r.img} alt={`${r.from} to ${r.to}`} className="h-full w-full object-cover transition duration-500 group-hover:scale-105"/><div className="absolute inset-0 bg-gradient-to-t from-black/75 via-black/5 to-transparent"/><span className="absolute left-4 top-4 rounded-full bg-white/90 px-3 py-2 text-xs font-bold text-ocean">◉ {r.from} → {r.to}</span><span className="absolute right-4 top-4 flex items-center gap-1 rounded-full bg-white/90 px-3 py-2 text-xs font-bold text-ocean"><Clock3 size={13}/>{r.time}</span><div className="absolute bottom-4 left-4 text-white"><h3 className="text-xl font-black">{r.from} → {r.to}</h3><p className="mt-1 text-sm font-semibold text-white/90">{r.description}</p></div></div><div className="flex min-h-[76px] items-center gap-3 p-3"><div className="flex min-w-0 flex-1 items-center gap-2 border-r border-slate-200 pr-2"><Ship size={20} className="shrink-0 text-ocean"/><span className="min-w-0"><b className="block truncate text-[11px] text-ocean">{r.feature}</b><small className="block truncate text-[10px] text-slate-500">{r.detail}</small></span></div><div className="hidden min-w-0 flex-1 items-center gap-2 sm:flex"><Users size={20} className="shrink-0 text-teal"/><span className="min-w-0"><b className="block truncate text-[11px] text-ocean">{r.second}</b><small className="block truncate text-[10px] text-slate-500">{r.secondDetail}</small></span></div><span className="grid h-9 w-9 shrink-0 place-items-center rounded-full bg-ocean text-white"><ArrowRight size={17}/></span></div></button>)}</div></section>}
