import React from 'react';
import {useNavigate} from 'react-router-dom';
import {ChevronDown,ArrowRight,ChevronRight,Clock,CheckCircle2,Ticket} from 'lucide-react';
import {Layout} from './Layout';
export function PageShell({title,kicker,children}){return <Layout><main className="container-page py-12"><p className="text-sm font-bold uppercase tracking-widest text-teal">{kicker}</p><h1 className="mt-2 text-4xl font-black tracking-tight">{title}</h1>{children}</main></Layout>}
export function Stats(){return <section className="bg-ocean py-16 text-white"><div className="container-page grid gap-8 sm:grid-cols-4">{[['150K+','Travelers served'],['50+','Ferry routes'],['99%','Customer satisfaction'],['24/7','Customer support']].map(([n,l])=><div key={l}><p className="text-4xl font-black">{n}</p><p className="mt-2 text-sm text-white/60">{l}</p></div>)}</div></section>}
export function FAQ(){return <section id="help" className="bg-white py-20"><div className="container-page grid gap-10 lg:grid-cols-2"><div><p className="mb-2 text-sm font-bold uppercase tracking-widest text-teal">Help</p><h2 className="section-title">Questions before you sail?</h2><p className="mt-4 max-w-lg text-slate-500">Find quick answers about booking, tickets, cancellations and your journey.</p><a href="/help" className="btn-primary mt-6 inline-flex">Visit Help Center</a></div><div className="space-y-3">{['How do I book a ferry?','Can I cancel or change my ticket?','Do I need a printed ticket?','What ID do I need to carry?','How much luggage can I take?'].map(q=><details className="group rounded-xl border border-slate-200 bg-white p-5" key={q}><summary className="flex cursor-pointer list-none items-center justify-between font-semibold">{q}<ChevronDown size={18} className="transition group-open:rotate-180"/></summary><p className="mt-3 text-sm leading-6 text-slate-500">Policies can vary by ferry operator. Your booking details show the applicable information before payment.</p></details>)}</div></div></section>}
export function RouteCard({route}){const nav=useNavigate(); return <button onClick={()=>nav(`/search?state=${encodeURIComponent(route.state)}&from=${encodeURIComponent(route.from)}&to=${encodeURIComponent(route.to)}`)} className="group overflow-hidden rounded-2xl border border-slate-100 bg-white text-left shadow-sm transition hover:-translate-y-1 hover:shadow-lg"><div className="h-40 overflow-hidden"><img src={route.img} alt={`${route.from} to ${route.to}`} className="h-full w-full object-cover transition duration-500 group-hover:scale-105"/></div><div className="p-5"><div className="flex items-start justify-between gap-3"><div><span className="mb-1 block text-xs font-bold uppercase tracking-wide text-teal">{route.state}</span><b className="block text-lg text-ocean">{route.from} ↔ {route.to}</b><p className="mt-1 text-sm text-slate-500">{route.time}</p></div><span className="rounded-full bg-teal/10 px-2.5 py-1 text-xs font-bold text-teal">{route.tag}</span></div><p className="mt-4 text-sm font-semibold text-slate-600">From ₹{route.price}</p></div></button>}
export function FerryRow({f}){const nav=useNavigate(); return <div className="rounded-2xl border bg-white p-5 shadow-sm"><div className="grid gap-5 md:grid-cols-[1fr_1fr_.7fr_auto] md:items-center"><div><b>{f.name}</b><div className="mt-2 flex flex-wrap gap-2">{f.amenities.map(a=><span className="rounded-full bg-mist px-2.5 py-1 text-xs text-slate-600" key={a}>{a}</span>)}</div></div><div className="flex items-center gap-4"><div><b className="text-xl">{f.depart}</b><p className="text-xs text-slate-500">{f.from}</p></div><span className="h-px w-8 bg-slate-200"/><div><b className="text-xl">{f.arrive}</b><p className="text-xs text-slate-500">{f.to}</p></div></div><div><p className="text-sm text-slate-500">{f.duration}</p><p className="font-bold text-teal">★ {f.rating}</p></div><div className="md:text-right"><b className="text-xl">₹{f.price}</b><p className="mb-3 text-xs text-slate-500">per passenger</p><button onClick={()=>nav('/ferry/sea-link-express')} className="btn-primary">Select <ChevronRight size={16}/></button></div></div></div>}
export function Summary(){return <aside className="h-fit rounded-2xl border bg-white p-6"><h2 className="font-bold">Your journey</h2><div className="mt-4 rounded-xl bg-mist p-4"><b>Mumbai → Mandwa</b><p className="mt-1 text-sm text-slate-500">12 Sep · 09:30 AM</p></div><div className="mt-5 flex justify-between"><span>Total</span><b>₹1,400</b></div></aside>}
export function BookingCard({status,route,date,time,id}){const nav=useNavigate(); return <div className="rounded-2xl border bg-white p-6"><div className="flex items-center justify-between"><span className={`rounded-full px-3 py-1 text-xs font-bold ${status==='Upcoming'?'bg-teal/10 text-teal':'bg-slate-100 text-slate-500'}`}>{status}</span><span className="text-xs text-slate-400">{id}</span></div><h2 className="mt-5 text-xl font-bold">{route}</h2><p className="mt-2 text-sm text-slate-500">{date} · {time}</p><button onClick={()=>nav('/ticket')} className="btn-secondary mt-5">View ticket <ArrowRight size={16}/></button></div>}
